app:
  name: go_online_shop
  port: ":4000"
  encryption:
    salt: 10

db:
  host: localhost
  port: 5432
  name: go_online_shop
  user: postgres
  password: postgres
  connection_pool:
    max_idle_connection: 10
    max_open_connection: 30
    max_lifetime_connection: 60 #second
    max_idleTime_connection: 60 #second